spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kebabdb
    username: kebab
    password: kebab123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Keep the database schema updated without dropping dat
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false  # Disable H2 console when using PostgreSQL